# Generated by Django 3.0.7 on 2020-08-23 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=200)),
                ('time_entry', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('pub_date', models.DateField()),
                ('begin_time', models.TimeField()),
                ('recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YearMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TimePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=64)),
                ('pub_date', models.DateField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='times.Category')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.Day')),
                ('year_month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='times.YearMonth')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='year_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='times.YearMonth'),
        ),
    ]
