# Generated by Django 3.0.7 on 2020-06-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='begin_time',
            field=models.DateTimeField(default='2020-06-30 06:30'),
            preserve_default=False,
        ),
    ]
