# Generated by Django 3.0.7 on 2020-06-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_day_begin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='begin_time',
            field=models.TimeField(default='06:30'),
        ),
    ]
