# Generated by Django 3.0.7 on 2020-06-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_auto_20200630_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='begin_time',
            field=models.TimeField(),
        ),
    ]
