# Generated by Django 3.0.7 on 2020-07-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0007_auto_20200630_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='year_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='times.YearMonth'),
        ),
    ]
